### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by rim-wood** [Loogeek/douban_Website#1]
使用的是什么版本的node以及npm 啊，mongodb呢？

**Comment by Loogeek** [comment]
我的是mac环境，node是4.2.1，npm是2.14.22，mongodb是3.0.7

**Comment by Loogeek** [comment]
@will-min 我的是mac环境，node是4.2.1，npm是2.14.22，mongodb是3.0.7

**Comment by rim-wood** [comment]
我再试试，npm install 有些包有问题，跑不起来

发自我的 iPhone
