### ISSUE TITLE
怎么从multipart/form-data获取到post参数的？

### ISSUE THREAD

**Issue by Shsgear** [Loogeek/douban_Website#2]
既然海报上传页form enctype类型是multipart/form-data,那么按理来说路由处理里save方法req.body是获取不到movie的，请问是怎么获取到的呢？
`exports.save = function(req, res) {
             var movieObj = req.body.movie;
             var id =movieObj._id;
           ......
`

下面是我的情况
1.未设置ectype='multipart/form-data'，默认application/x-www-form-urlencoded
表单正常通过formData post参数
Form-Data:

> movie[categoryName]:
> movie[category]:590d979e8ab6903a1c46bcda
> movie[title]:机器人9号
> movie[doctor]:申·阿克
> movie[country]:美国
> movie[language]:
> movie[poster]:https://img1.doubanio.com/view/movie_poster_cover/lpst/public/p494268647.jpg
> uploadPoster:b922270259dece707ef6c6a50259a406_r.png
> movie[flash]:
> movie[year]:2009
但是不能上传文件

2.设置了ectype='multipart/form-data'
可以上传文件，但是表单中普通文本域不再通过formData传送给后台，（通过request.payload）所以后台使用req.body报undefined

**Comment by FanWalker** [comment]
@Shsgear 
我的方法是：
先 `npm install multer --save`
在routes.js文件下引入
```
var multer = require('multer');
var upload = multer({dest: 'public/upload/'})   //这里dest定义的是存放的目标文件夹
```
在下面的路由：
`app.post('/admin/movie/new',User.signinRequired, User.adminRequired,upload.single('uploadPoster'), Movie.savePoster, Movie.save)`
添加中间件`upload.single('uploadPoster')` uploadPoster是input的name属性；
到controllers文件下的movie.js的savePoster下：
```
	var posterData = req.file    //req.file是"uploadPoster"文件信息
	console.log(posterData)       //查看posterData具体信息
	var filePath = posterData.path    
	var originalFilename = posterData.originalname //文件原始名字
	if(originalFilename){   //有文件名字，判断文件上传
		fs.readFile(filePath, function(err, data){
			var timestamp = Date.now()
			var type = posterData.mimetype.split('/')[1]
			var poster = timestamp + '.' + type
			var newPath = path.join(__dirname,'../../','/public/upload/'+poster)
			console.log('新路径为：'+newPath)
			fs.writeFile(newPath,data,function(err){
				req.poster = poster
				next()
			})
		})
	}
	else{
		next()
	}
```
更多的Multer中间件可以到这里查看[node.js 中间件](https://github.com/expressjs/multer/blob/master/doc/README-zh-cn.md)
