### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by Missshao** [Loogeek/douban_Website#3]
请问这个项目有docker image吗？ 装node的模块 好多依赖很不方便。

**Comment by Loogeek** [comment]
不好意思，这项目有一段时间没维护了，目前没有

**Comment by Loogeek** [comment]
@Missshao 不好意思，这项目有一段时间没维护了，目前没有

**Comment by Loogeek** [comment]
@Missshao 不好意思，这项目有一段时间没维护了，目前不支持
